CREATE TABLE bulletin_feedback (
  id VARCHAR(50) NOT NULL,
  bulletin_id VARCHAR(50) DEFAULT NULL,
  member_id VARCHAR(50) DEFAULT NULL,
  checked TINYINT(1) DEFAULT NULL,
  remark VARCHAR(255) DEFAULT NULL,
  created_at DATETIME DEFAULT NULL,
  updated_at DATETIME DEFAULT NULL,
  deleted_at DATETIME DEFAULT NULL,
  INDEX IDX_A02DF056D1AAB236 (bulletin_id),
  INDEX IDX_A02DF0567597D3FE (member_id),
  PRIMARY KEY(id)
) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;

ALTER TABLE bulletin_feedback ADD CONSTRAINT FK_A02DF056D1AAB236 FOREIGN KEY (bulletin_id) REFERENCES bulletin (id);

ALTER TABLE bulletin_feedback ADD CONSTRAINT FK_A02DF0567597D3FE FOREIGN KEY (member_id) REFERENCES member (id);
